/*
 * Java
 *
 * Copyright 2020 MicroEJ Corp. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be found with this software.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppMessage.proto

package com.microej.example.protobuf3example;

public final class AppProto {
	private AppProto() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	/**
	 * Protobuf enum {@code com.microej.example.protobuf3example.Encryption}
	 */
	public enum Encryption implements com.google.protobuf.Internal.EnumLite {
		/**
		 * <code>NONE = 0;</code>
		 */
		NONE(0),
		/**
		 * <code>PGP = 1;</code>
		 */
		PGP(1),
		/**
		 * <code>SMIME = 2;</code>
		 */
		SMIME(2), UNRECOGNIZED(-1),;

		/**
		 * <code>NONE = 0;</code>
		 */
		public static final int NONE_VALUE = 0;
		/**
		 * <code>PGP = 1;</code>
		 */
		public static final int PGP_VALUE = 1;
		/**
		 * <code>SMIME = 2;</code>
		 */
		public static final int SMIME_VALUE = 2;

		@Override
		public final int getNumber() {
			return this.value;
		}

		/**
		 * @deprecated Use {@link #forNumber(int)} instead.
		 */
		@java.lang.Deprecated
		public static Encryption valueOf(int value) {
			return forNumber(value);
		}

		public static Encryption forNumber(int value) {
			switch (value) {
			case 0:
				return NONE;
			case 1:
				return PGP;
			case 2:
				return SMIME;
			default:
				return null;
			}
		}

		public static com.google.protobuf.Internal.EnumLiteMap<Encryption> internalGetValueMap() {
			return internalValueMap;
		}

		private static final com.google.protobuf.Internal.EnumLiteMap<Encryption> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<Encryption>() {
			@Override
			public Encryption findValueByNumber(int number) {
				return Encryption.forNumber(number);
			}
		};

		private final int value;

		private Encryption(int value) {
			this.value = value;
		}

		// @@protoc_insertion_point(enum_scope:com.microej.example.protobuf3example.Encryption)
	}

	public interface AppMessageOrBuilder extends
			// @@protoc_insertion_point(interface_extends:com.microej.example.protobuf3example.AppMessage)
			com.google.protobuf.MessageLiteOrBuilder {

		/**
		 * <code>optional int32 id = 1;</code>
		 */
		int getId();

		/**
		 * <code>optional string subject = 2;</code>
		 */
		java.lang.String getSubject();

		/**
		 * <code>optional string subject = 2;</code>
		 */
		com.google.protobuf.ByteString getSubjectBytes();

		/**
		 * <code>optional string messageContent = 3;</code>
		 */
		java.lang.String getMessageContent();

		/**
		 * <code>optional string messageContent = 3;</code>
		 */
		com.google.protobuf.ByteString getMessageContentBytes();

		/**
		 * <code>optional .google.protobuf.Timestamp date = 4;</code>
		 */
		boolean hasDate();

		/**
		 * <code>optional .google.protobuf.Timestamp date = 4;</code>
		 */
		com.google.protobuf.Timestamp getDate();

		/**
		 * <code>optional .com.microej.example.protobuf3example.Encryption encryption = 5;</code>
		 */
		int getEncryptionValue();

		/**
		 * <code>optional .com.microej.example.protobuf3example.Encryption encryption = 5;</code>
		 */
		com.microej.example.protobuf3example.AppProto.Encryption getEncryption();
	}

	/**
	 * Protobuf type {@code com.microej.example.protobuf3example.AppMessage}
	 */
	public static final class AppMessage extends com.google.protobuf.GeneratedMessageLite<AppMessage, AppMessage.Builder>
			implements
			// @@protoc_insertion_point(message_implements:com.microej.example.protobuf3example.AppMessage)
			AppMessageOrBuilder {
		private AppMessage() {
			this.subject_ = "";
			this.messageContent_ = "";
		}

		public static final int ID_FIELD_NUMBER = 1;
		private int id_;

		/**
		 * <code>optional int32 id = 1;</code>
		 */
		@Override
		public int getId() {
			return this.id_;
		}

		/**
		 * <code>optional int32 id = 1;</code>
		 */
		private void setId(int value) {

			this.id_ = value;
		}

		/**
		 * <code>optional int32 id = 1;</code>
		 */
		private void clearId() {

			this.id_ = 0;
		}

		public static final int SUBJECT_FIELD_NUMBER = 2;
		private java.lang.String subject_;

		/**
		 * <code>optional string subject = 2;</code>
		 */
		@Override
		public java.lang.String getSubject() {
			return this.subject_;
		}

		/**
		 * <code>optional string subject = 2;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getSubjectBytes() {
			return com.google.protobuf.ByteString.copyFromUtf8(this.subject_);
		}

		/**
		 * <code>optional string subject = 2;</code>
		 */
		private void setSubject(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			this.subject_ = value;
		}

		/**
		 * <code>optional string subject = 2;</code>
		 */
		private void clearSubject() {

			this.subject_ = getDefaultInstance().getSubject();
		}

		/**
		 * <code>optional string subject = 2;</code>
		 */
		private void setSubjectBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			this.subject_ = value.toStringUtf8();
		}

		public static final int MESSAGECONTENT_FIELD_NUMBER = 3;
		private java.lang.String messageContent_;

		/**
		 * <code>optional string messageContent = 3;</code>
		 */
		@Override
		public java.lang.String getMessageContent() {
			return this.messageContent_;
		}

		/**
		 * <code>optional string messageContent = 3;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getMessageContentBytes() {
			return com.google.protobuf.ByteString.copyFromUtf8(this.messageContent_);
		}

		/**
		 * <code>optional string messageContent = 3;</code>
		 */
		private void setMessageContent(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			this.messageContent_ = value;
		}

		/**
		 * <code>optional string messageContent = 3;</code>
		 */
		private void clearMessageContent() {

			this.messageContent_ = getDefaultInstance().getMessageContent();
		}

		/**
		 * <code>optional string messageContent = 3;</code>
		 */
		private void setMessageContentBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			this.messageContent_ = value.toStringUtf8();
		}

		public static final int DATE_FIELD_NUMBER = 4;
		private com.google.protobuf.Timestamp date_;

		/**
		 * <code>optional .google.protobuf.Timestamp date = 4;</code>
		 */
		@Override
		public boolean hasDate() {
			return this.date_ != null;
		}

		/**
		 * <code>optional .google.protobuf.Timestamp date = 4;</code>
		 */
		@Override
		public com.google.protobuf.Timestamp getDate() {
			return this.date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : this.date_;
		}

		/**
		 * <code>optional .google.protobuf.Timestamp date = 4;</code>
		 */
		private void setDate(com.google.protobuf.Timestamp value) {
			if (value == null) {
				throw new NullPointerException();
			}
			this.date_ = value;

		}

		/**
		 * <code>optional .google.protobuf.Timestamp date = 4;</code>
		 */
		private void setDate(com.google.protobuf.Timestamp.Builder builderForValue) {
			this.date_ = builderForValue.build();

		}

		/**
		 * <code>optional .google.protobuf.Timestamp date = 4;</code>
		 */
		private void mergeDate(com.google.protobuf.Timestamp value) {
			if (this.date_ != null && this.date_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
				this.date_ = com.google.protobuf.Timestamp.newBuilder(this.date_).mergeFrom(value).buildPartial();
			} else {
				this.date_ = value;
			}

		}

		/**
		 * <code>optional .google.protobuf.Timestamp date = 4;</code>
		 */
		private void clearDate() {
			this.date_ = null;

		}

		public static final int ENCRYPTION_FIELD_NUMBER = 5;
		private int encryption_;

		/**
		 * <code>optional .com.microej.example.protobuf3example.Encryption encryption = 5;</code>
		 */
		@Override
		public int getEncryptionValue() {
			return this.encryption_;
		}

		/**
		 * <code>optional .com.microej.example.protobuf3example.Encryption encryption = 5;</code>
		 */
		@Override
		public com.microej.example.protobuf3example.AppProto.Encryption getEncryption() {
			com.microej.example.protobuf3example.AppProto.Encryption result = com.microej.example.protobuf3example.AppProto.Encryption
					.forNumber(this.encryption_);
			return result == null ? com.microej.example.protobuf3example.AppProto.Encryption.UNRECOGNIZED : result;
		}

		/**
		 * <code>optional .com.microej.example.protobuf3example.Encryption encryption = 5;</code>
		 */
		private void setEncryptionValue(int value) {
			this.encryption_ = value;
		}

		/**
		 * <code>optional .com.microej.example.protobuf3example.Encryption encryption = 5;</code>
		 */
		private void setEncryption(com.microej.example.protobuf3example.AppProto.Encryption value) {
			if (value == null) {
				throw new NullPointerException();
			}

			this.encryption_ = value.getNumber();
		}

		/**
		 * <code>optional .com.microej.example.protobuf3example.Encryption encryption = 5;</code>
		 */
		private void clearEncryption() {

			this.encryption_ = 0;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (this.id_ != 0) {
				output.writeInt32(1, this.id_);
			}
			if (!this.subject_.isEmpty()) {
				output.writeString(2, getSubject());
			}
			if (!this.messageContent_.isEmpty()) {
				output.writeString(3, getMessageContent());
			}
			if (this.date_ != null) {
				output.writeMessage(4, getDate());
			}
			if (this.encryption_ != com.microej.example.protobuf3example.AppProto.Encryption.NONE.getNumber()) {
				output.writeEnum(5, this.encryption_);
			}
		}

		@Override
		public int getSerializedSize() {
			int size = this.memoizedSerializedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			if (this.id_ != 0) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, this.id_);
			}
			if (!this.subject_.isEmpty()) {
				size += com.google.protobuf.CodedOutputStream.computeStringSize(2, getSubject());
			}
			if (!this.messageContent_.isEmpty()) {
				size += com.google.protobuf.CodedOutputStream.computeStringSize(3, getMessageContent());
			}
			if (this.date_ != null) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(4, getDate());
			}
			if (this.encryption_ != com.microej.example.protobuf3example.AppProto.Encryption.NONE.getNumber()) {
				size += com.google.protobuf.CodedOutputStream.computeEnumSize(5, this.encryption_);
			}
			this.memoizedSerializedSize = size;
			return size;
		}

		public static com.microej.example.protobuf3example.AppProto.AppMessage parseFrom(
				com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
		}

		public static com.microej.example.protobuf3example.AppProto.AppMessage parseFrom(
				com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data, extensionRegistry);
		}

		public static com.microej.example.protobuf3example.AppProto.AppMessage parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
		}

		public static com.microej.example.protobuf3example.AppProto.AppMessage parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data, extensionRegistry);
		}

		public static com.microej.example.protobuf3example.AppProto.AppMessage parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
		}

		public static com.microej.example.protobuf3example.AppProto.AppMessage parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input, extensionRegistry);
		}

		public static com.microej.example.protobuf3example.AppProto.AppMessage parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return parseDelimitedFrom(DEFAULT_INSTANCE, input);
		}

		public static com.microej.example.protobuf3example.AppProto.AppMessage parseDelimitedFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
		}

		public static com.microej.example.protobuf3example.AppProto.AppMessage parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
		}

		public static com.microej.example.protobuf3example.AppProto.AppMessage parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(com.microej.example.protobuf3example.AppProto.AppMessage prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		/**
		 * Protobuf type {@code com.microej.example.protobuf3example.AppMessage}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageLite.Builder<com.microej.example.protobuf3example.AppProto.AppMessage, Builder>
				implements
				// @@protoc_insertion_point(builder_implements:com.microej.example.protobuf3example.AppMessage)
				com.microej.example.protobuf3example.AppProto.AppMessageOrBuilder {
			// Construct using com.microej.example.protobuf3example.AppProto.AppMessage.newBuilder()
			private Builder() {
				super(DEFAULT_INSTANCE);
			}

			/**
			 * <code>optional int32 id = 1;</code>
			 */
			@Override
			public int getId() {
				return this.instance.getId();
			}

			/**
			 * <code>optional int32 id = 1;</code>
			 */
			public Builder setId(int value) {
				copyOnWrite();
				this.instance.setId(value);
				return this;
			}

			/**
			 * <code>optional int32 id = 1;</code>
			 */
			public Builder clearId() {
				copyOnWrite();
				this.instance.clearId();
				return this;
			}

			/**
			 * <code>optional string subject = 2;</code>
			 */
			@Override
			public java.lang.String getSubject() {
				return this.instance.getSubject();
			}

			/**
			 * <code>optional string subject = 2;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getSubjectBytes() {
				return this.instance.getSubjectBytes();
			}

			/**
			 * <code>optional string subject = 2;</code>
			 */
			public Builder setSubject(java.lang.String value) {
				copyOnWrite();
				this.instance.setSubject(value);
				return this;
			}

			/**
			 * <code>optional string subject = 2;</code>
			 */
			public Builder clearSubject() {
				copyOnWrite();
				this.instance.clearSubject();
				return this;
			}

			/**
			 * <code>optional string subject = 2;</code>
			 */
			public Builder setSubjectBytes(com.google.protobuf.ByteString value) {
				copyOnWrite();
				this.instance.setSubjectBytes(value);
				return this;
			}

			/**
			 * <code>optional string messageContent = 3;</code>
			 */
			@Override
			public java.lang.String getMessageContent() {
				return this.instance.getMessageContent();
			}

			/**
			 * <code>optional string messageContent = 3;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getMessageContentBytes() {
				return this.instance.getMessageContentBytes();
			}

			/**
			 * <code>optional string messageContent = 3;</code>
			 */
			public Builder setMessageContent(java.lang.String value) {
				copyOnWrite();
				this.instance.setMessageContent(value);
				return this;
			}

			/**
			 * <code>optional string messageContent = 3;</code>
			 */
			public Builder clearMessageContent() {
				copyOnWrite();
				this.instance.clearMessageContent();
				return this;
			}

			/**
			 * <code>optional string messageContent = 3;</code>
			 */
			public Builder setMessageContentBytes(com.google.protobuf.ByteString value) {
				copyOnWrite();
				this.instance.setMessageContentBytes(value);
				return this;
			}

			/**
			 * <code>optional .google.protobuf.Timestamp date = 4;</code>
			 */
			@Override
			public boolean hasDate() {
				return this.instance.hasDate();
			}

			/**
			 * <code>optional .google.protobuf.Timestamp date = 4;</code>
			 */
			@Override
			public com.google.protobuf.Timestamp getDate() {
				return this.instance.getDate();
			}

			/**
			 * <code>optional .google.protobuf.Timestamp date = 4;</code>
			 */
			public Builder setDate(com.google.protobuf.Timestamp value) {
				copyOnWrite();
				this.instance.setDate(value);
				return this;
			}

			/**
			 * <code>optional .google.protobuf.Timestamp date = 4;</code>
			 */
			public Builder setDate(com.google.protobuf.Timestamp.Builder builderForValue) {
				copyOnWrite();
				this.instance.setDate(builderForValue);
				return this;
			}

			/**
			 * <code>optional .google.protobuf.Timestamp date = 4;</code>
			 */
			public Builder mergeDate(com.google.protobuf.Timestamp value) {
				copyOnWrite();
				this.instance.mergeDate(value);
				return this;
			}

			/**
			 * <code>optional .google.protobuf.Timestamp date = 4;</code>
			 */
			public Builder clearDate() {
				copyOnWrite();
				this.instance.clearDate();
				return this;
			}

			/**
			 * <code>optional .com.microej.example.protobuf3example.Encryption encryption = 5;</code>
			 */
			@Override
			public int getEncryptionValue() {
				return this.instance.getEncryptionValue();
			}

			/**
			 * <code>optional .com.microej.example.protobuf3example.Encryption encryption = 5;</code>
			 */
			public Builder setEncryptionValue(int value) {
				copyOnWrite();
				this.instance.setEncryptionValue(value);
				return this;
			}

			/**
			 * <code>optional .com.microej.example.protobuf3example.Encryption encryption = 5;</code>
			 */
			@Override
			public com.microej.example.protobuf3example.AppProto.Encryption getEncryption() {
				return this.instance.getEncryption();
			}

			/**
			 * <code>optional .com.microej.example.protobuf3example.Encryption encryption = 5;</code>
			 */
			public Builder setEncryption(com.microej.example.protobuf3example.AppProto.Encryption value) {
				copyOnWrite();
				this.instance.setEncryption(value);
				return this;
			}

			/**
			 * <code>optional .com.microej.example.protobuf3example.Encryption encryption = 5;</code>
			 */
			public Builder clearEncryption() {
				copyOnWrite();
				this.instance.clearEncryption();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:com.microej.example.protobuf3example.AppMessage)
		}

		@Override
		@java.lang.SuppressWarnings("unchecked")
		protected final Object dynamicMethod(com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
				Object arg0, Object arg1) {
			switch (method) {
			case NEW_MUTABLE_INSTANCE: {
				return new com.microej.example.protobuf3example.AppProto.AppMessage();
			}
			case IS_INITIALIZED: {
				return DEFAULT_INSTANCE;
			}
			case MAKE_IMMUTABLE: {
				return null;
			}
			case NEW_BUILDER: {
				return new Builder();
			}
			case VISIT: {
				Visitor visitor = (Visitor) arg0;
				com.microej.example.protobuf3example.AppProto.AppMessage other = (com.microej.example.protobuf3example.AppProto.AppMessage) arg1;
				this.id_ = visitor.visitInt(this.id_ != 0, this.id_, other.id_ != 0, other.id_);
				this.subject_ = visitor.visitString(!this.subject_.isEmpty(), this.subject_, !other.subject_.isEmpty(),
						other.subject_);
				this.messageContent_ = visitor.visitString(!this.messageContent_.isEmpty(), this.messageContent_,
						!other.messageContent_.isEmpty(), other.messageContent_);
				this.date_ = visitor.visitMessage(this.date_, other.date_);
				this.encryption_ = visitor.visitInt(this.encryption_ != 0, this.encryption_, other.encryption_ != 0,
						other.encryption_);
				if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor.INSTANCE) {
				}
				return this;
			}
			case MERGE_FROM_STREAM: {
				com.google.protobuf.CodedInputStream input = (com.google.protobuf.CodedInputStream) arg0;
				com.google.protobuf.ExtensionRegistryLite extensionRegistry = (com.google.protobuf.ExtensionRegistryLite) arg1;
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
						case 0:
							done = true;
							break;
						default: {
							if (!input.skipField(tag)) {
								done = true;
							}
							break;
						}
						case 8: {

							this.id_ = input.readInt32();
							break;
						}
						case 18: {
							String s = input.readStringRequireUtf8();

							this.subject_ = s;
							break;
						}
						case 26: {
							String s = input.readStringRequireUtf8();

							this.messageContent_ = s;
							break;
						}
						case 34: {
							com.google.protobuf.Timestamp.Builder subBuilder = null;
							if (this.date_ != null) {
								subBuilder = this.date_.toBuilder();
							}
							this.date_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
							if (subBuilder != null) {
								subBuilder.mergeFrom(this.date_);
								this.date_ = subBuilder.buildPartial();
							}

							break;
						}
						case 40: {
							int rawValue = input.readEnum();

							this.encryption_ = rawValue;
							break;
						}
						}
					}
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw new RuntimeException(e.setUnfinishedMessage(this));
				} catch (java.io.IOException e) {
					throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
							.setUnfinishedMessage(this));
				} finally {
				}
			}
			// fall through
			case GET_DEFAULT_INSTANCE: {
				return DEFAULT_INSTANCE;
			}
			case GET_PARSER: {
				if (PARSER == null) {
					synchronized (com.microej.example.protobuf3example.AppProto.AppMessage.class) {
						if (PARSER == null) {
							PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
						}
					}
				}
				return PARSER;
			}
			}
			throw new UnsupportedOperationException();
		}

		// @@protoc_insertion_point(class_scope:com.microej.example.protobuf3example.AppMessage)
		private static final com.microej.example.protobuf3example.AppProto.AppMessage DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new AppMessage();
			DEFAULT_INSTANCE.makeImmutable();
		}

		public static com.microej.example.protobuf3example.AppProto.AppMessage getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static volatile com.google.protobuf.Parser<AppMessage> PARSER;

		public static com.google.protobuf.Parser<AppMessage> parser() {
			return DEFAULT_INSTANCE.getParserForType();
		}
	}

	static {
	}

	// @@protoc_insertion_point(outer_class_scope)
}
